# Setup
title:               Tuan Nguyen
tagline:             'Stop talking start building'
description:         'Blog share something from <a href="https://tuannguyendang.github.io/blog/" target="_blank">Tuan Nguyen</a> for some one coder. Made by <a href="https://www.linkedin.com/in/tuan-nguyen-dang-b97b8366/" target="_blank">tuan193@gmail.com</a>.'
url:                 https://tuannguyendang.github.io/blog
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Tuan Nguyen
  url:               https://www.linkedin.com/in/tuan-nguyen-dang-b97b8366/
  email:             tuan193@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
